export const APP_TEXT = {
  newCategory: 'New Category',
  categoryName: 'Category Name',
  field: 'Field',
  addNewField: 'Add New Field',
  remove: 'Remove',
  text: 'Text',
  date: 'Date',
  number: 'Number',
  checkbox: 'Checkbox',
  addACategory: 'Add a category',
  noCategoriesFound: 'No Categories Found',
  addItem: 'Add Item',
  manageCategories: 'Manage Categories',
  unnamedField: 'Unnamed Field',
  unnamedCategory: 'Unnamed Category',
  titleField: 'Title Field',
  titleNA: 'Title N/A',
  noData: 'No data in this section.',
};
